name: 'Ionic Dev Build'

on:
  workflow_dispatch:

jobs:
  dev-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Install Dependencies
        run: npm install
        shell: bash
      - name: Prepare
        run: lerna bootstrap -- --legacy-peer-deps
        shell: bash
      - name: Create Dev Build
        run: lerna publish --no-verify-access --yes --ignore-scripts --force-publish='*' --canary --dist-tag dev --preid dev
        shell: bash
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
